### PR TITLE
added my profile card

### PR DESCRIPTION
**Pull request by Pisces2802**
Hello Hassana, I just added my profile to your code base and I also added my picture to the asset folder as stipulated in the readme.MD file. Kindly go over my code base to review the changes.

### CODE REVIEW

**Review by hassana123 — APPROVED** [review]
Thanks for contributing to this project

**Comment by hassana123** [comment]
@Pisces2802  though Idea was to create a unique profile card for yourself but this is acceptable to ☺

**Comment by Pisces2802** [comment]
Ohhh, I’ll do that, thanks.. expect a another pull request soon.

**Comment by hassana123** [comment]
Okay great ☺

**Pull request merged**
