### PR TITLE
added my profile card

### PR DESCRIPTION
**Pull request by estherbabe**
Hi Hassana Just contributed to your project, kindly accept my pull request

### CODE REVIEW

**Comment by hassana123** [comment]
@estherbabe thanks for contributing 😊

**Comment by hassana123** [comment]
> Hi Hassana Just contributed to your project, kindly accept my pull request


Kindly request a review

**Review by hassana123 — APPROVED** [review]
Great work

**Comment by hassana123** [comment]
@estherbabe  it will be great if you can make your profile card unique

**Comment by estherbabe** [comment]
> @estherbabe thanks for contributing 😊

Thanks for having me. please kindly give me a follow on here, i follow back

**Comment by estherbabe** [comment]
> @estherbabe it will be great if you can make your profile card unique

alright I'll work on it later 
let me try to contribute to 3 other projects as requested by AltSchool

**Comment by hassana123** [comment]
> > @estherbabe thanks for contributing 😊
> 
> Thanks for having me. please kindly give me a follow on here, i follow back

Sure 😊

**Pull request merged**
